# Generated by Django 5.0.3 on 2024-03-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='r_number',
            new_name='Room_number',
        ),
    ]
