# Generated by Django 4.2.5 on 2024-03-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable_App', '0002_rename_r_number_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('seating_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('start_time', models.CharField(choices=[('8:00 - 8:50', '8:50 - 9:40'), ('9:40 - 10:30', '10:45 - 11:30'), ('12:05 - 12:50', '12:50 - 1:35'), ('1:45 - 2:30', '2:30 - 3:15 ')], max_length=20)),
                ('end_time', models.CharField(choices=[('8:00 - 8:50', '8:50 - 9:40'), ('9:40 - 10:30', '10:45 - 11:30'), ('12:05 - 12:50', '12:50 - 1:35'), ('1:45 - 2:30', '2:30 - 3:15 ')], max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='department',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='section',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='section',
            name='room',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_numb_students',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='uid',
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='preferred_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='preferred_end_time',
            field=models.CharField(blank=True, choices=[('8:00 - 8:50', '8:50 - 9:40'), ('9:40 - 10:30', '10:45 - 11:30'), ('12:05 - 12:50', '12:50 - 1:35'), ('1:45 - 2:30', '2:30 - 3:15 ')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='preferred_start_time',
            field=models.CharField(blank=True, choices=[('8:00 - 8:50', '8:50 - 9:40'), ('9:40 - 10:30', '10:45 - 11:30'), ('12:05 - 12:50', '12:50 - 1:35'), ('1:45 - 2:30', '2:30 - 3:15 ')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='MeetingTime',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
