# Generated by Django 5.0.4 on 2024-04-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable_App', '0006_rename_course_number_course_course_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
