# Generated by Django 5.0.4 on 2024-04-28 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable_App', '0008_class_classroom_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_days', models.IntegerField()),
                ('classes', models.ManyToManyField(related_name='timetables', to='Timetable_App.class')),
                ('classrooms', models.ManyToManyField(related_name='timetables', to='Timetable_App.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('instructor_name', models.CharField(max_length=100)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable_App.timetable')),
            ],
        ),
    ]
