# Generated by Django 5.0.4 on 2024-04-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable_App', '0009_timetable_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='classrooms',
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('period', models.IntegerField()),
                ('class_field', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable_App.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable_App.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable_App.instructor')),
            ],
        ),
        migrations.DeleteModel(
            name='Association',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
